FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS build

WORKDIR /tests
COPY src/Tests/BlackBox/{{API_NAME}}.Tests.BlackBox.csproj ./
RUN dotnet restore {{API_NAME}}.Tests.BlackBox.csproj
COPY src/Tests/BlackBox/ ./
RUN dotnet format {{API_NAME}}.Tests.BlackBox.csproj --verify-no-changes --no-restore
RUN dotnet build {{API_NAME}}.Tests.BlackBox.csproj --no-restore --configuration Release -warnaserror

ENTRYPOINT ["dotnet", "test", "{{API_NAME}}.Tests.BlackBox.csproj", "--no-build", "--no-restore", "--configuration", "Release"]
